package language.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Attribute_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Boolean_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Entity_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Integer_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new String_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xab7f4811201f4d6dL, 0xa13e8542b1519f5fL, 0x519d01a09492a2edL), MetaIdFactory.conceptId(0xab7f4811201f4d6dL, 0xa13e8542b1519f5fL, 0x519d01a09492a2f9L), MetaIdFactory.conceptId(0xab7f4811201f4d6dL, 0xa13e8542b1519f5fL, 0x519d01a09492a2eaL), MetaIdFactory.conceptId(0xab7f4811201f4d6dL, 0xa13e8542b1519f5fL, 0x519d01a09492a2faL), MetaIdFactory.conceptId(0xab7f4811201f4d6dL, 0xa13e8542b1519f5fL, 0x519d01a09492a2fbL)).seal();
}
