package language.sandbox;

/*Generated by MPS */

import java.io.Serializable;

public class Usuario implements Serializable {

  private String id;
  private String nombre;
  private int edad;
  private boolean premium;

  public Usuario(String id, String nombre, int edad, boolean premium) {
    this.id = id;
    this.nombre = nombre;
    this.edad = edad;
    this.premium = premium;
  }

  public Usuario() {
  }

  public String getId() {
    return this.id;
  }
  public String getNombre() {
    return this.nombre;
  }
  public int getEdad() {
    return this.edad;
  }
  public boolean isPremium() {
    return this.premium;
  }

  public void setId(String id) {
    this.id = id;
  }
  public void setNombre(String nombre) {
    this.nombre = nombre;
  }
  public void setEdad(int edad) {
    this.edad = edad;
  }
  public void setPremium(boolean premium) {
    this.premium = premium;
  }

  @Override
  public String toString() {
    StringBuffer buffer = new StringBuffer();
    buffer.append("Usuario").append(" [");
    buffer.append("id").append("=").append(id);
    buffer.append("nombre").append("=").append(nombre);
    buffer.append("edad").append("=").append(edad);
    buffer.append("premium").append("=").append(premium);
    buffer.append("]");
    return buffer.toString();
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null || this.getClass() != obj.getClass()) {
      return false;
    }

    Usuario other = (Usuario) obj;
    if (id != other.id) {
      return false;
    }
    if (nombre != other.nombre) {
      return false;
    }
    if (edad != other.edad) {
      return false;
    }
    if (premium != other.premium) {
      return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int result = 0;
    result = 31 * result + id;
    return result;
  }
}
